
services:
  database:
    image: postgres:17.6
    container_name: database
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio-cms
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"

  redis:
    image: redis:latest
    container_name: redis-cms
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  database_pgdata: { }
  redisdata: { }
  miniodata: { }